apiVersion: v1
kind: Namespace

metadata:
  name: my-ns
---
apiVersion: v1
kind: Service
metadata:
  name: my-svc
  namespace: my-ns
spec:
  selector:
    app: my-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
kind: Secret
apiVersion: v1

metadata:
  name: mysql-sec
  namespace: my-ns

type: opaque
stringData:  # Use stringData to put plain text; K8s will encode it for you
#  password: "QWRtaW5AJCUxMjM="
  host: "database-1.cih84c6osdd0.us-east-1.rds.amazonaws.com"
  user: "admin"
  dbname: "devops_db" # Update this from 'mysql' to your new database name # Based on your 'show databases' output
#data:
#  password: QWRtaW5AJCUxMjM= # echo -n "Admin@$%123" | base64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dep
  namespace: my-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-web
  template:
    metadata:
      labels:
        app: my-web
    spec:
      serviceAccountName: rds-auth-sa
      containers:
      - name: my-pod
        image: yashmane108/simple-app:REPLACE_ME
        resources:
          requests:
            memory: "64Mi"   # Guaranteed 64 Megabytes
            cpu: "100m"      # 10% of 1 CPU core
          limits:
            memory: "128Mi"  # Hard cap at 128 Megabytes
            cpu: "500m"       # Max 50% of 1 CPU core
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-sec
              key: host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-sec
              key: user
      #  - name: DB_PASSWORD
     #     valueFrom:
    #        secretKeyRef:
    #         name: mysql-sec
     #         key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-sec
              key: dbname
        # --- ADD PROBES BELOW ---
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ing
  namespace: my-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-svc
            port:
              number: 80

